name: 'vmtest'
description: 'Programmatically run tests in a virtualized machine'
author: 'danobi'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
